languageCode = "en-us"
title = "bazhenovc"
baseurl = "https://bazhenovc.github.io/blog/"
disqusShortname = "bazhenovcsblog"
theme = "dream"

[params]
  author = "Kirill Bazhenov"
  motto = ""
  description = "Game development rants"
  avatar = ""

  email = ""
  github = ""
  linkedin = ""
  codepen = ""
  stackoverflow = ""
