languageCode = "en-us"
title = "bazhenovc"
baseurl = "https://bazhenovc.github.io/blog/"
disqusShortname = "bazhenovcsblog"
theme = "dream"

[params]
  author = "Kirill Bazhenov" // Site author or as default article author
  motto = ""
  description = "Game development rants" // <meta name="description" content="">
  avatar = "" // your logo

  email = ""
  github = ""
  linkedin = ""
  codepen = ""
  stackoverflow = ""
